/// Generates `docs/<scraped-directory>/` — a structured reference tree that Copilot reads
/// when directed to by the user's own `copilot-instructions.md`.
///
/// Output layout:
///   docs/<scraped-directory>/
///     INDEX.md          — module map + how to read this tree
///     vocabulary.md     — enums (the API's composable vocabulary)
///     types.md          — structs with fields and methods
///     traits.md         — traits and their required methods
///     functions.md      — public free functions
///     misc.md           — type aliases and constants (omitted if empty)
///     api-graph.json    — full machine-readable dump
///
/// Add this to your existing copilot-instructions.md:
///   Before generating any [Engine] code, review `docs/<scraped-directory>/INDEX.md`
///   and the relevant files in that directory for available types, enum variants,
///   and API constraints.
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::Result;

use crate::model::{ApiItem, ApiMethod, ApiVariant, ItemKind};

pub struct ContextFiles {
    /// Relative path → file contents.
    pub files: BTreeMap<PathBuf, String>,
}

pub fn render(items: &[ApiItem], engine_name: &str, out_dir: &Path) -> Result<ContextFiles> {
    let mut files: BTreeMap<PathBuf, String> = BTreeMap::new();

    // Split items by kind
    let structs:   Vec<_> = items.iter().filter(|i| i.kind == ItemKind::Struct).collect();
    let enums:     Vec<_> = items.iter().filter(|i| i.kind == ItemKind::Enum).collect();
    let traits:    Vec<_> = items.iter().filter(|i| i.kind == ItemKind::Trait).collect();
    let fns:       Vec<_> = items.iter().filter(|i| i.kind == ItemKind::Function).collect();
    let misc:      Vec<_> = items.iter()
        .filter(|i| matches!(i.kind, ItemKind::TypeAlias | ItemKind::Const))
        .collect();

    // INDEX.md — entry point Copilot reads first
    files.insert(out_dir.join("INDEX.md"), render_index(items, engine_name, &structs, &enums, &traits, &fns, &misc));

    // vocabulary.md — enums are the most important: they define what the API *can express*
    if !enums.is_empty() {
        files.insert(out_dir.join("vocabulary.md"), render_vocabulary(&enums, engine_name));
    }

    // types.md — structs with fields and methods
    if !structs.is_empty() {
        files.insert(out_dir.join("types.md"), render_types(&structs, engine_name));
    }

    // traits.md
    if !traits.is_empty() {
        files.insert(out_dir.join("traits.md"), render_traits(&traits, engine_name));
    }

    // functions.md
    if !fns.is_empty() {
        files.insert(out_dir.join("functions.md"), render_functions(&fns, engine_name));
    }

    // misc.md — only written if there's something in it
    if !misc.is_empty() {
        files.insert(out_dir.join("misc.md"), render_misc(&misc, engine_name));
    }

    // api-graph.json
    files.insert(
        out_dir.join("api-graph.json"),
        serde_json::to_string_pretty(items)?,
    );

    Ok(ContextFiles { files })
}

// ── INDEX.md ──────────────────────────────────────────────────────────────────

fn render_index(
    items: &[ApiItem],
    engine_name: &str,
    structs: &[&ApiItem],
    enums: &[&ApiItem],
    traits: &[&ApiItem],
    fns: &[&ApiItem],
    misc: &[&ApiItem],
) -> String {
    let mut s = String::new();

    l(&mut s, &format!("# {} API Context Index\n", engine_name));
    l(&mut s, &format!(
        "> Auto-generated by `quartz-ctx` from `{}` source.\n\
         > Do not edit manually — re-run `quartz-ctx` to refresh.\n",
        engine_name
    ));

    l(&mut s, "## How to Use This Reference\n");
    l(&mut s, &format!(
        "- **`vocabulary.md`** — Start here. Contains every enum and its variants.\n\
         - **`types.md`** — Struct shapes, public fields, and their methods.\n\
         - **`traits.md`** — Trait definitions and required method signatures.\n\
         - **`functions.md`** — Public free functions.\n\
         - **`api-graph.json`** — Full machine-readable API graph.\n\
         \n\
         When writing {} code: check `vocabulary.md` first for the correct enum variant \
         to express your intent, then `types.md` to understand the data shape.\n",
        engine_name
    ));

    // Module map
    let mut by_module: BTreeMap<String, Vec<&ApiItem>> = BTreeMap::new();
    for item in items {
        by_module.entry(item.module_str()).or_default().push(item);
    }

    l(&mut s, "## Module Map\n");
    for (module, module_items) in &by_module {
        let label = if module.is_empty() { "crate root" } else { module.as_str() };
        let names: String = module_items.iter()
            .map(|i| format!("`{}`", i.name))
            .collect::<Vec<_>>()
            .join(", ");
        l(&mut s, &format!("- **`{}`** — {}\n", label, names));
    }
    s.push('\n');

    // Quick-ref tables per kind
    quick_ref_table(&mut s, "Enums (vocabulary)", enums);
    quick_ref_table(&mut s, "Structs (types)", structs);
    quick_ref_table(&mut s, "Traits", traits);
    quick_ref_table(&mut s, "Functions", fns);
    if !misc.is_empty() {
        quick_ref_table(&mut s, "Aliases & Constants", misc);
    }

    s
}

fn quick_ref_table(s: &mut String, heading: &str, items: &[&ApiItem]) {
    if items.is_empty() { return; }
    l(s, &format!("### {}\n", heading));
    l(s, "| Name | Summary |\n");
    l(s, "|------|---------|\n");
    for item in items {
        l(s, &format!("| `{}` | {} |\n", item.name, item.doc_summary()));
    }
    s.push('\n');
}

// ── vocabulary.md ─────────────────────────────────────────────────────────────

fn render_vocabulary(enums: &[&ApiItem], engine_name: &str) -> String {
    let mut s = String::new();
    l(&mut s, &format!("# {} — API Vocabulary (Enums)\n", engine_name));
    l(&mut s, "These enums define what the engine can express. \
               **Prefer a variant here over raw data or booleans.**\n");

    for e in enums {
        l(&mut s, &format!("## `{}`\n", e.name));
        if !e.doc.is_empty() {
            l(&mut s, &format!("{}\n", e.doc));
        }

        if !e.variants.is_empty() {
            l(&mut s, "| Variant | Fields | Description |\n");
            l(&mut s, "|---------|--------|-------------|\n");
            for v in &e.variants {
                let fields = v.fields_inline();
                let fields_col = if fields.is_empty() { "—".into() } else { format!("`{}`", fields) };
                l(&mut s, &format!(
                    "| `{}::{}` | {} | {} |\n",
                    e.name, v.name, fields_col, v.doc_summary()
                ));
            }
            s.push('\n');

            // Expand variants with multiple fields into their own sub-sections
            let detailed: Vec<_> = e.variants.iter().filter(|v| v.fields.len() > 1).collect();
            if !detailed.is_empty() {
                l(&mut s, "### Field Detail\n");
                for v in detailed {
                    variant_detail(&mut s, &e.name, v);
                }
            }
        }

        if !e.methods.is_empty() {
            method_list(&mut s, &e.methods);
        }
    }

    s
}

fn variant_detail(s: &mut String, enum_name: &str, v: &ApiVariant) {
    l(s, &format!("#### `{}::{}`\n", enum_name, v.name));
    if !v.doc.is_empty() { l(s, &format!("{}\n", v.doc)); }
    l(s, "| Field | Type | Description |\n");
    l(s, "|-------|------|-------------|\n");
    for f in &v.fields {
        let name = if f.name.starts_with('_') { "(positional)".into() } else { format!("`{}`", f.name) };
        l(s, &format!("| {} | `{}` | {} |\n", name, f.ty, f.doc));
    }
    s.push('\n');
}

// ── types.md ──────────────────────────────────────────────────────────────────

fn render_types(structs: &[&ApiItem], engine_name: &str) -> String {
    let mut s = String::new();
    l(&mut s, &format!("# {} — Types (Structs)\n", engine_name));

    for item in structs {
        l(&mut s, &format!("## `{}`\n", item.name));
        if !item.module_str().is_empty() {
            l(&mut s, &format!("_module: `{}`_\n", item.module_str()));
        }
        if !item.doc.is_empty() { l(&mut s, &format!("{}\n", item.doc)); }

        l(&mut s, &format!("```rust\n{}\n```\n", item.signature));

        if !item.fields.is_empty() {
            l(&mut s, "\n**Fields**\n");
            l(&mut s, "| Field | Type | Description |\n");
            l(&mut s, "|-------|------|-------------|\n");
            for f in &item.fields {
                l(&mut s, &format!("| `{}` | `{}` | {} |\n", f.name, f.ty, f.doc));
            }
            s.push('\n');
        }

        if !item.methods.is_empty() {
            method_list(&mut s, &item.methods);
        }

        if !item.traits_impl.is_empty() {
            l(&mut s, &format!("**Implements:** {}\n\n", item.traits_impl.join(", ")));
        }
    }

    s
}

// ── traits.md ─────────────────────────────────────────────────────────────────

fn render_traits(traits: &[&ApiItem], engine_name: &str) -> String {
    let mut s = String::new();
    l(&mut s, &format!("# {} — Traits\n", engine_name));

    for item in traits {
        l(&mut s, &format!("## `{}`\n", item.name));
        if !item.doc.is_empty() { l(&mut s, &format!("{}\n", item.doc)); }
        l(&mut s, &format!("```rust\n{}\n```\n", item.signature));

        if !item.methods.is_empty() {
            l(&mut s, "\n**Required Methods**\n");
            for m in &item.methods {
                l(&mut s, &format!("### `{}`\n", m.name));
                if !m.doc.is_empty() { l(&mut s, &format!("{}\n", m.doc)); }
                l(&mut s, &format!("```rust\n{}\n```\n", m.signature));
            }
        }
        s.push('\n');
    }

    s
}

// ── functions.md ──────────────────────────────────────────────────────────────

fn render_functions(fns: &[&ApiItem], engine_name: &str) -> String {
    let mut s = String::new();
    l(&mut s, &format!("# {} — Public Functions\n", engine_name));

    for f in fns {
        l(&mut s, &format!("## `{}`\n", f.name));
        if !f.module_str().is_empty() {
            l(&mut s, &format!("_module: `{}`_\n", f.module_str()));
        }
        if !f.doc.is_empty() { l(&mut s, &format!("{}\n", f.doc)); }
        l(&mut s, &format!("```rust\n{}\n```\n\n", f.signature));
    }

    s
}

// ── misc.md ───────────────────────────────────────────────────────────────────

fn render_misc(items: &[&ApiItem], engine_name: &str) -> String {
    let mut s = String::new();
    l(&mut s, &format!("# {} — Type Aliases & Constants\n", engine_name));

    for item in items {
        l(&mut s, &format!("## `{}`  _({})\n_", item.name, item.kind.label()));
        if !item.doc.is_empty() { l(&mut s, &format!("{}\n", item.doc)); }
        l(&mut s, &format!("```rust\n{}\n```\n\n", item.signature));
    }

    s
}

// ── Shared helpers ────────────────────────────────────────────────────────────

fn method_list(s: &mut String, methods: &[ApiMethod]) {
    l(s, "**Methods**\n");
    for m in methods {
        l(s, &format!("### `{}`\n", m.name));
        if !m.doc.is_empty() { l(s, &format!("{}\n", m.doc)); }
        l(s, &format!("```rust\n{}\n```\n", m.signature));
    }
    s.push('\n');
}

fn l(s: &mut String, line: &str) {
    s.push_str(line);
    if !line.ends_with('\n') { s.push('\n'); }
}
