/// Renders the human-readable API reference files in `docs/<scraped-directory>/`.
/// Organized by kind, with full signatures, field tables, method lists, and doc text.
use crate::model::{ApiItem, ItemKind};

pub fn render(items: &[ApiItem], engine_name: &str) -> String {
    let mut out = String::new();

    push(&mut out, &format!("# {} API Reference\n", engine_name));
    push(&mut out, "_Auto-generated by `quartz-ctx`. Do not edit manually._\n");

    // Table of contents
    push(&mut out, "## Contents\n");
    for (label, kind) in &[
        ("Structs",          ItemKind::Struct),
        ("Enums",            ItemKind::Enum),
        ("Traits",           ItemKind::Trait),
        ("Functions",        ItemKind::Function),
        ("Type Aliases",     ItemKind::TypeAlias),
        ("Constants",        ItemKind::Const),
    ] {
        if items.iter().any(|i| &i.kind == kind) {
            push(&mut out, &format!("- [{}](#{})\n", label, label.to_lowercase().replace(' ', "-")));
        }
    }
    out.push('\n');

    render_kind(&mut out, items, ItemKind::Struct,    "Structs",      render_struct);
    render_kind(&mut out, items, ItemKind::Enum,      "Enums",        render_enum);
    render_kind(&mut out, items, ItemKind::Trait,     "Traits",       render_trait);
    render_kind(&mut out, items, ItemKind::Function,  "Functions",    render_fn);
    render_kind(&mut out, items, ItemKind::TypeAlias, "Type Aliases", render_simple);
    render_kind(&mut out, items, ItemKind::Const,     "Constants",    render_simple);

    out
}

// ── Section dispatcher ────────────────────────────────────────────────────────

fn render_kind(
    out: &mut String,
    items: &[ApiItem],
    kind: ItemKind,
    heading: &str,
    render_item: fn(&mut String, &ApiItem),
) {
    let subset: Vec<_> = items.iter().filter(|i| i.kind == kind).collect();
    if subset.is_empty() {
        return;
    }
    push(out, &format!("## {}\n", heading));
    for item in subset {
        render_item(out, item);
    }
}

// ── Per-kind renderers ────────────────────────────────────────────────────────

fn render_struct(out: &mut String, item: &ApiItem) {
    section_header(out, &item.name, &item.module_str());
    doc_block(out, &item.doc);

    push(out, "```rust\n");
    push(out, &item.signature);
    push(out, "\n```\n");

    if !item.fields.is_empty() {
        push(out, "\n**Fields**\n\n");
        push(out, "| Field | Type | Description |\n");
        push(out, "|-------|------|-------------|\n");
        for f in &item.fields {
            push(out, &format!("| `{}` | `{}` | {} |\n", f.name, f.ty, f.doc));
        }
    }

    render_methods(out, &item.methods);
    render_trait_impls(out, &item.traits_impl);
    out.push('\n');
}

fn render_enum(out: &mut String, item: &ApiItem) {
    section_header(out, &item.name, &item.module_str());
    doc_block(out, &item.doc);

    push(out, "```rust\n");
    push(out, &item.signature);
    push(out, "\n```\n");

    if !item.variants.is_empty() {
        push(out, "\n**Variants**\n\n");
        for v in &item.variants {
            let fields_str = v.fields_inline();
            if fields_str.is_empty() {
                push(out, &format!("#### `{}`\n", v.name));
            } else {
                push(out, &format!("#### `{}` `{}`\n", v.name, fields_str));
            }
            if !v.doc.is_empty() {
                push(out, &format!("{}\n\n", v.doc));
            }
            if !v.fields.is_empty() {
                push(out, "| Field | Type | Description |\n");
                push(out, "|-------|------|-------------|\n");
                for f in &v.fields {
                    if !f.name.starts_with('_') {
                        push(out, &format!("| `{}` | `{}` | {} |\n", f.name, f.ty, f.doc));
                    } else {
                        push(out, &format!("| (positional) | `{}` | {} |\n", f.ty, f.doc));
                    }
                }
                out.push('\n');
            }
        }
    }

    render_methods(out, &item.methods);
    render_trait_impls(out, &item.traits_impl);
    out.push('\n');
}

fn render_trait(out: &mut String, item: &ApiItem) {
    section_header(out, &item.name, &item.module_str());
    doc_block(out, &item.doc);
    push(out, "```rust\n");
    push(out, &item.signature);
    push(out, "\n```\n");

    if !item.methods.is_empty() {
        push(out, "\n**Required Methods**\n\n");
        for m in &item.methods {
            push(out, &format!("##### `{}`\n", m.name));
            if !m.doc.is_empty() {
                push(out, &format!("{}\n\n", m.doc));
            }
            push(out, &format!("```rust\n{}\n```\n\n", m.signature));
        }
    }
    out.push('\n');
}

fn render_fn(out: &mut String, item: &ApiItem) {
    section_header(out, &item.name, &item.module_str());
    doc_block(out, &item.doc);
    push(out, &format!("```rust\n{}\n```\n\n", item.signature));
}

fn render_simple(out: &mut String, item: &ApiItem) {
    push(out, &format!("### `{}`\n", item.name));
    doc_block(out, &item.doc);
    push(out, &format!("```rust\n{}\n```\n\n", item.signature));
}

// ── Shared helpers ────────────────────────────────────────────────────────────

fn section_header(out: &mut String, name: &str, module: &str) {
    push(out, &format!("### `{}`\n", name));
    if !module.is_empty() {
        push(out, &format!("_module: `{}`_\n\n", module));
    }
}

fn doc_block(out: &mut String, doc: &str) {
    if !doc.is_empty() {
        push(out, &format!("{}\n\n", doc));
    }
}

fn render_methods(out: &mut String, methods: &[crate::model::ApiMethod]) {
    if methods.is_empty() {
        return;
    }
    push(out, "\n**Methods**\n\n");
    for m in methods {
        push(out, &format!("##### `{}`\n", m.name));
        if !m.doc.is_empty() {
            push(out, &format!("{}\n\n", m.doc));
        }
        push(out, &format!("```rust\n{}\n```\n\n", m.signature));
    }
}

fn render_trait_impls(out: &mut String, traits: &[String]) {
    if !traits.is_empty() {
        push(out, &format!("**Implements:** {}\n", traits.join(", ")));
    }
}

fn push(s: &mut String, text: &str) {
    s.push_str(text);
    if !text.is_empty() && !text.ends_with('\n') {
        s.push('\n');
    }
}
