// Anti-patterns database extracted from quartz_ai_api_cache and copilot-instructions.md
// These represent common mistakes that cause bugs, performance issues, or compile errors.

use crate::model::AntiPattern;

pub fn get_all_anti_patterns() -> Vec<AntiPattern> {
    vec![
        AntiPattern {
            name: "Double Borrow in Text Creation".to_string(),
            description: "Calling canvas.make_text() inside a get_game_object_mut() borrow scope causes a double borrow compile error.".to_string(),
            wrong_code: "if let Some(obj) = canvas.get_game_object_mut(\"label\") {\n    obj.set_drawable(Box::new(canvas.make_text(...)));\n}".to_string(),
            correct_code: "let txt = canvas.make_text(...);\nif let Some(obj) = canvas.get_game_object_mut(\"label\") {\n    obj.set_drawable(Box::new(txt));\n}".to_string(),
            consequence: "Compile error: cannot borrow canvas as mutable twice".to_string(),
            affected_types: vec!["Canvas".to_string(), "GameObject".to_string()],
        },
        AntiPattern {
            name: "Direct Prism Imports".to_string(),
            description: "Importing from prism directly instead of using quartz::prelude breaks encapsulation and causes confusion.".to_string(),
            wrong_code: "use prism::canvas::Color;".to_string(),
            correct_code: "use quartz::prelude::*;".to_string(),
            consequence: "API inconsistency, harder to maintain, may break with updates".to_string(),
            affected_types: vec!["Color".to_string(), "Text".to_string()],
        },
        AntiPattern {
            name: "SetPosition Zeroes Momentum".to_string(),
            description: "Using Action::SetPosition for smooth movement breaks physics because it resets momentum to zero.".to_string(),
            wrong_code: "canvas.run(Action::SetPosition { target, x, y });".to_string(),
            correct_code: "canvas.run(Action::Teleport { target, location: Location::at(x, y) });\n// Or use apply_momentum for smooth movement".to_string(),
            consequence: "Object stops abruptly, physics stops working, jumps feel unresponsive".to_string(),
            affected_types: vec!["Action".to_string()],
        },
        AntiPattern {
            name: "Custom Physics Instead of Crystalline".to_string(),
            description: "Building custom physics logic instead of using the Crystalline solver wastes effort and creates bugs.".to_string(),
            wrong_code: "obj.momentum.0 += gravity * dt;\n// manual collision solving...".to_string(),
            correct_code: "canvas.run(Action::EnableCrystalline);\n// Engine handles XPBD solver, broadphase, sleep, contacts".to_string(),
            consequence: "Physics is unreliable, performs poorly, hard to debug".to_string(),
            affected_types: vec!["GameObject".to_string(), "Canvas".to_string()],
        },
        AntiPattern {
            name: "Spring-Based Grapple Instead of GrappleConstraint".to_string(),
            description: "Building grapples with spring forces instead of using GrappleConstraint causes elastic/floaty behavior.".to_string(),
            wrong_code: "obj.momentum.0 += (anchor.0 - pos.0) * spring_k;".to_string(),
            correct_code: "let grapple = GrappleConstraint::new(obj_id, anchor);\nlet correction = grapple.solve(pos, vel);".to_string(),
            consequence: "Rope feels floaty and elastic instead of rigid, rope constraints don't hold properly".to_string(),
            affected_types: vec!["GrappleConstraint".to_string()],
        },
        AntiPattern {
            name: "Direct Camera Position Instead of Follow".to_string(),
            description: "Setting camera.position directly fights the engine's camera follow system and causes jittery behavior.".to_string(),
            wrong_code: "camera.position = (player_x - CW/2.0, 0.0);".to_string(),
            correct_code: "camera.follow(Some(Target::name(\"player\"))); // lerp_speed for smoothness".to_string(),
            consequence: "Camera jitters, doesn't follow smoothly, conflicts with follow lerp".to_string(),
            affected_types: vec!["Camera".to_string()],
        },
        AntiPattern {
            name: "Collision Layer Zero Disables Dynamic Collision".to_string(),
            description: "Using layer 0 for objects disables dynamic-to-dynamic collision detection.".to_string(),
            wrong_code: "obj.build(\"bullet\").collision_layer(0).finish();".to_string(),
            correct_code: ".collision_layer(collision_layers::PROJECTILE) // Use named layers".to_string(),
            consequence: "Objects don't collide with each other, physics fails silently".to_string(),
            affected_types: vec!["GameObject".to_string()],
        },
        AntiPattern {
            name: "Missing Hooked Flag Check Before Release".to_string(),
            description: "Calling ReleaseGrapple without checking hooked status can cause undefined behavior.".to_string(),
            wrong_code: "hooked = false; // Doesn't call ReleaseGrapple".to_string(),
            correct_code: "canvas.run(Action::ReleaseGrapple { target, ... });".to_string(),
            consequence: "Grapple state inconsistent, rope physics broken".to_string(),
            affected_types: vec!["Action".to_string()],
        },
        AntiPattern {
            name: "Entropy::range() with Integer Literals".to_string(),
            description: "Calling Entropy::range() with integer literals instead of f32 causes type errors.".to_string(),
            wrong_code: "Entropy::range(0, 10) // integers".to_string(),
            correct_code: "Entropy::range(0.0, 10.0) // f32".to_string(),
            consequence: "Compile error, entropy values don't generate correctly".to_string(),
            affected_types: vec!["Entropy".to_string()],
        },
        AntiPattern {
            name: "Shared<T> Ref Held Across get_mut()".to_string(),
            description: "Holding a Shared<T>::get() reference and calling get_mut() on the same object panics at runtime.".to_string(),
            wrong_code: "let ref_a = shared.get();\nlet mut_b = shared.get_mut(); // PANIC".to_string(),
            correct_code: "{\n    let ref_a = shared.get();\n    // use ref_a\n}\nlet mut_b = shared.get_mut(); // OK, ref_a dropped".to_string(),
            consequence: "Runtime panic, application crash".to_string(),
            affected_types: vec!["Shared".to_string()],
        },
        AntiPattern {
            name: "Manual Camera Flash Overlay".to_string(),
            description: "Setting camera flash overlay manually instead of using CameraEffects conflicts with engine management.".to_string(),
            wrong_code: "canvas.set_variable(\"__quartz_flash_overlay\", ...); // DO NOT".to_string(),
            correct_code: "canvas.camera_mut()?.flash(FlashEffect { ... });".to_string(),
            consequence: "Flash effects don't render, conflicts with engine state".to_string(),
            affected_types: vec!["Camera".to_string(), "CameraEffects".to_string()],
        },
        // ─ Phase 1 additions from api.txt ─
        AntiPattern {
            name: "Text Creation Inside get_game_object_mut Borrow".to_string(),
            description: "Calling make_text() inside get_game_object_mut() scope causes runtime borrow panic (both borrow canvas mutably).".to_string(),
            wrong_code: "if let Some(obj) = cv.get_game_object_mut(\"label\") {\n    let t = c.make_text(\"hello\", 32.0, Color::white(), ...);\n    obj.set_drawable(Box::new(t));\n}".to_string(),
            correct_code: "let t = c.make_text(\"hello\", 32.0, Color::white(), ...);\nif let Some(obj) = c.get_game_object_mut(\"label\") {\n    obj.set_drawable(Box::new(t));\n}".to_string(),
            consequence: "Runtime panic: 'attempted to borrow Canvas while already mutably borrowed'".to_string(),
            affected_types: vec!["Canvas".to_string(), "make_text".to_string()],
        },
        AntiPattern {
            name: "Large Object Uniform Tinting from Center".to_string(),
            description: "Large background objects (e.g., 30000+ width) get uniform tint from center point, making lighting pointless.".to_string(),
            wrong_code: "let bg = GameObject::build(\"bg\")\n    .size(30000.0, 2160.0)\n    .add_light(light)  // entire object gets one color\n    .finish();".to_string(),
            correct_code: "let bg = GameObject::build(\"bg\")\n    .size(30000.0, 2160.0)\n    .unlit()  // no lighting, always full brightness\n    .finish();".to_string(),
            consequence: "Entire large object gets one color regardless of position; lighting variation impossible".to_string(),
            affected_types: vec!["GameObject".to_string(), "add_light".to_string()],
        },
        AntiPattern {
            name: "Modifier-Only Key Press Never Fires".to_string(),
            description: "Pressing Ctrl/Shift/Alt alone never triggers on_key_press callbacks (modifiers tracked but not fired as events).".to_string(),
            wrong_code: "cv.on_key_press(|cv, key| {\n    match key {\n        Key::Named(NamedKey::Control) => println!(\"Ctrl\"),  // NEVER FIRES\n        _ => {}\n    }\n});".to_string(),
            correct_code: "cv.on_key_press(|cv, key| {\n    if let Key::Character(ch) = key {\n        let ctrl = cv.is_key_held(&Key::Named(NamedKey::Control));\n        if ctrl { println!(\"Ctrl+{}\", ch); }\n    }\n});".to_string(),
            consequence: "on_key_press never fires for Ctrl/Shift/Alt/Meta alone; must check modifiers inside callback".to_string(),
            affected_types: vec!["Canvas".to_string(), "Key".to_string()],
        },
        AntiPattern {
            name: "Entropy::range() with Integer Argument".to_string(),
            description: "Entropy::range() only accepts f32, not integer literals (common mistake from number generation patterns).".to_string(),
            wrong_code: "let mut rng = Entropy::new();\nlet rand = rng.range(0, 100);  // ERROR: type mismatch".to_string(),
            correct_code: "let mut rng = Entropy::new();\nlet rand = rng.range(0.0, 100.0);  // f32 literals".to_string(),
            consequence: "Compilation error: expected f32, found integer literal".to_string(),
            affected_types: vec!["Entropy".to_string()],
        },
        AntiPattern {
            name: "Hot-Reload Poll Latency Expectation".to_string(),
            description: "File changes are NOT detected immediately; hot-reload poll interval is 0.5 seconds.".to_string(),
            wrong_code: "cv.watch_file(\"config.toml\", |..| { ... });\n// Immediately expect file changes (but 0.5s delay exists)".to_string(),
            correct_code: "cv.watch_file(\"config.toml\", |..| { ... });\n// File changes detected within 0.5s poll interval (design, not bug)".to_string(),
            consequence: "File changes not detected for up to 0.5s; if testing, account for latency".to_string(),
            affected_types: vec!["Canvas".to_string(), "watch_file".to_string()],
        },
        AntiPattern {
            name: "Object Pool Partial Reset Assumptions".to_string(),
            description: "pool_acquire resets ONLY position and momentum, not other properties (rotation, color, animation, scale).".to_string(),
            wrong_code: "let name = cv.pool_acquire(\"bullets\", pos).unwrap();\n// Assume object fully reset (rotation, color, etc.)".to_string(),
            correct_code: "let name = cv.pool_acquire(\"bullets\", pos).unwrap();\n// Manually reset: rotation, color, animation, scale\nif let Some(obj) = cv.get_game_object_mut(&name) {\n    obj.set_rotation(0.0);\n    obj.set_color(Color(255,255,255,255));\n}".to_string(),
            consequence: "Pool objects retain properties from previous use; not fully reset as expected".to_string(),
            affected_types: vec!["Canvas".to_string(), "pool_acquire".to_string()],
        },
        AntiPattern {
            name: "KeyHold Fires with Modifiers Held".to_string(),
            description: "KeyHold events ONLY fire when NO modifiers are held; held with Ctrl/Shift/Alt will NOT fire.".to_string(),
            wrong_code: "// Expecting KeyHold to fire for Ctrl+A\n// But KeyHold ONLY fires when no modifiers held".to_string(),
            correct_code: "// For Ctrl+A, catch on_key_press(A) and check cv.is_key_held(Ctrl)".to_string(),
            consequence: "KeyHold events never fire for modifier combinations; use on_key_press for those".to_string(),
            affected_types: vec!["Canvas".to_string(), "GameEvent".to_string()],
        },
        AntiPattern {
            name: "Physics Step Before Camera Transform".to_string(),
            description: "Physics (step 8) runs BEFORE camera transform (step 11), so camera reads final post-physics positions.".to_string(),
            wrong_code: "// Expecting camera to read velocities BEFORE physics resolution".to_string(),
            correct_code: "// Physics runs at step 8, camera reads final state at step 11".to_string(),
            consequence: "Misunderstanding timing leads to incorrect velocity predictions or race conditions".to_string(),
            affected_types: vec!["Canvas".to_string(), "Camera".to_string()],
        },
        AntiPattern {
            name: "Boundary Collision Events Fire Last".to_string(),
            description: "Boundary collision events (step 13) fire LAST after all physics/camera updates, not during physics.".to_string(),
            wrong_code: "// Expecting boundary collision to affect camera position same frame".to_string(),
            correct_code: "// Boundary events fire at step 13 (last); if immediate effect needed, handle in on_update".to_string(),
            consequence: "Boundary wrapping/cleanup delayed by one frame or not applied as expected".to_string(),
            affected_types: vec!["Canvas".to_string(), "GameEvent".to_string()],
        },
        AntiPattern {
            name: "Text Layout Caching by Hash".to_string(),
            description: "Text layout is cached by content hash; changing only color is cheap, but changing layout parameters clears cache.".to_string(),
            wrong_code: "// Rebuilding text every frame for dynamic size/content".to_string(),
            correct_code: "// Build text once, modify color only (uses cache). Recreate only if content/size/font changes.".to_string(),
            consequence: "Unnecessary cache misses, performance degradation on large text updates".to_string(),
            affected_types: vec!["Text".to_string(), "make_text".to_string()],
        },
        AntiPattern {
            name: "Assuming Full GameEvent Reset in pool_acquire".to_string(),
            description: "pool_acquire resets position/momentum but NOT game event callbacks or state flags.".to_string(),
            wrong_code: "pool_acquire(\"enemies\", pos);  // Assume all state reset".to_string(),
            correct_code: "pool_acquire(\"enemies\", pos);\n// Manually clear: animation index, state flags, callbacks".to_string(),
            consequence: "Pooled objects inherit state from previous use; bugs from stale callbacks or flags".to_string(),
            affected_types: vec!["Canvas".to_string(), "pool_acquire".to_string()],
        },
        AntiPattern {
            name: "Flash Overlay Manual Management".to_string(),
            description: "Camera flash overlay (__quartz_flash_overlay) is engine-managed; manual creation/modification breaks effects.".to_string(),
            wrong_code: "canvas.set_variable(\"__quartz_flash_overlay\", ...); // DO NOT".to_string(),
            correct_code: "canvas.camera_mut()?.flash(FlashEffect { ... });".to_string(),
            consequence: "Flash effects don't render correctly, conflicts with engine state".to_string(),
            affected_types: vec!["Camera".to_string(), "CameraEffects".to_string()],
        },
    ]
}

pub fn find_anti_patterns_for_type(type_name: &str) -> Vec<&'static AntiPattern> {
    // This would be called at runtime with the static list
    // For now, returns matching patterns
    vec![]
}
